name: Automation Test CRM

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run API Test
        run: ./gradlew apiTest

      - name: Run Web Test
        run: ./gradlew webTest

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/